package ExceptionHandling.ArithmeticException


object Main extends App{
  val e = new Exception
  e.divide(20, 4)
}
